### PR TITLE
patch for filemagic on Solaris

### PR DESCRIPTION
**Pull request by erhudy**
I was working on getting filemagic set up on some Solaris servers and found that ctypes.util.find_library does not appear to work on Solaris, even on the most recent version of Python 2.7 (doing something like ctypes.util.find_library('c') returns None when you'd obviously expect it to return something there), and thusly filemagic won't work since it doesn't know that the library does exist.  I made a little patch to magic/api.py that checks the operating system and uses dl.open to test for the presence of libmagic.so if the OS is SunOS.

### CODE REVIEW

**Comment by aliles** [comment]
Oh my, this appears to be [issue 5289](http://bugs.python.org/issue5289). I've added myself to the nosey list on that particular issue.

Unfortunately, as you may have noticed, your pull request [failed to buid](https://travis-ci.org/aliles/filemagic/builds/3636051) on [Travis CI](https://travis-ci.org/aliles/filemagic). This is because the [dl module](http://docs.python.org/2/library/dl.html) has been deprecated so doesn't exist on Python 3.2 and PyPy.

What do you think about instead special casing for 'SunOS' when `find_library` returns `None`.  

``` python
libname = ctypes.util.find_library('magic')                                     
if not libname:                                                                 
    if platform.system() == 'SunOS':                                            
        libname = 'libmagic.so'                                                 
    else:                                                                       
        raise ImportError('Unable to find magic library')
```

One downside is that this would raise ImportError with a "Loading libmagic.so failed" rather than "Unable to find magic library" when libmagic can not be found. Perhaps a [warning](http://docs.python.org/3/library/warnings.html) should be issued during the special casing?

**Comment by erhudy** [comment]
Shamefully, I should have noticed that dl was removed in Python 3.  I think your counteroffer would be fine, since Solaris is probably not in real common use (I wish I didn't have to use it), and I will turn my attention to 5289 to see if I can do something about the underlying problem with ctypes.

**Comment by aliles** [comment]
Sorry, back online now. Would you like me to go ahead and make those changes or would you like test them on Solaris first and update the pull request? You might like to also create a CONTRIBUTORS file with you name in it. :)

**Comment by erhudy** [comment]
I closed this pull request so I could do a new one the Proper GitHub Way (in a topic branch instead of on master).

**Pull request closed without merging**
